borazslo/miserend.hu

functions.php, templates2/home.twig, templates2/layout.twig, templates2/panel.twig
Middle column for small screens (bootstrap class named "sm") was extremely narrow (2 of 12). Modified email link to fit into box.
=> fixing column widths for small screens

README.md, composer.json, composer.lock, moduls/miserend.php
Installed website on a fresh linux machine. I got empty answer from install.php because I had no msql php extension installed. Included mysql and sqlite in composer requirements.
There was a string "Array" displayed near church image because $kepek variable was an array when html was concatenated to it. Initialized as an empty string.
=> small fixes

css/style.css, moduls/miserend.php, templates2/doboz_lila.html
These tables are terrible, much better would be using bootstrap grids.
=> simplifying html formatting with css

classes/Html/Church.php, css/style.css, templates2/doboz_lila.html
Tried to use the simplest markup.
=> replacing nested tables with divs

install.php
making it executable, avoiding warning about password, printing output to stderr, simplifying mkdir commands
=> improving installer

bower.json, classes/Html/Home.php, templates2/home.twig
Added bootstrap-datepicker component. Deleted inactive code from template.
=> datepicker

classes/api/sqlite.php, classes/eloquent/cron.php, classes/html/cron.php
Rettentő lassú az Api / SqLite és sürgősen kéne vele valamit csinálni.
=> cron / sqlite hot fix

classes/eloquent/cron.php, classes/html/user/catalogue.php, classes/html/user/edit.php, classes/keywordshortcut.php, classes/user.php, templates/user/edit.twig
does it contain the solution for "cannot fork"?
=> cron + user/edit

.htaccess, Vagrantfile, classes/api/api.php, classes/api/report.php, classes/api/reportbyanonym.php, classes/api/upload.php, classes/eloquent/favorite.php, classes/eloquent/photo.php, classes/eloquent/token.php, classes/html/api.php, classes/html/apitest.php, classes/html/church/church.php, classes/html/home.php, classes/html/html.php, classes/remark.php, classes/user.php, functions.php, mysql_sample.sql, package.json, templates/apitest.twig
- API-n keresztüli megjegyzések már jól működnek
- API-n keresztül lehet képet is feltölteni
- Az API-val lehet játszani admin felületen keresztül
=> API javítások és fejlesztések

templates/church/_photoslide.twig, templates/home.twig, templates/layout.twig
Néhány oldalhoz elkészítettem a lazy loading hozzáadását az img-hez!
=> Optimalizált képbetöltődés

css/style.css, templates/church/_panelcontact.twig, templates/layout.twig, templates/panel.twig
Mobil nézetben is láthatóak lesznek a kisebb dobozok a templom adatlap oldalon
=> Eszrevetel mobilfix

docker-compose.yml
Ez a PR elvileg javítja a #160 issue-t.
Figyelem! **Nem teszteltem**, hogy működik-e ha elindulnak a konténerek, de a hibát az elején nem írja már a terminál.
fix #160
=> Docker hiba javítása fix #160

.gitattributes
szerintem ez megoldja a sorvég problémát clone-kor
=> .gitattributes file alapok

composer.json, composer.lock
Elkezdem aktívabban küldeni PR-okat.
=> [composer] csomag frissítések

.github/workflows/symfony.yml
=> [github] teszteles workflow

.gitignore, composer.json, composer.lock, phpunit.xml.dist, symfony.lock, tests/bootstrap.php
Ha a #192 bement, akkor ezen még csinálok valamit és akkor mehet ez is.
=> [tests] fussanak azok a tesztek

composer.json
=> [composer] ext-gd-vel jelezzuk, hogy ezt hasznalja a site

assets/css/_bootstrap.scss, assets/css/_variables.scss, assets/css/app.scss, assets/js/app.js
megcsinaltam az alap bootstrap buildet par alap fajllal egyutt, hogy lathato legyen mi a cel a bootstrappel
=> [style] bootstrap customize és scss változók

composer.json, phpunit.xml.dist, src/Components/ApiClients/CommunitiesApiClient.php, src/Components/ApiClients/Exceptions/ContentUnavailableException.php, src/Components/ApiClients/Response/CommunitiesResponse.php, src/Components/ApiClients/Response/Community.php, src/Components/ApiClients/Tests/CommunitiesApiClientTest.php, src/Components/ApiClients/Tests/Fixtures/404_response.json, src/Components/ApiClients/Tests/Fixtures/empty_data.json, src/Components/ApiClients/Tests/Fixtures/full_data.json, src/Components/ApiClients/Tests/Twig/Runtime/CommunitiesExtensionRuntimeTest.php, src/Components/ApiClients/Twig/Extension/CommunitiesExtension.php, src/Components/ApiClients/Twig/Runtime/CommunitiesExtensionRuntime.php
hibakezelése és néhány kapcsolódó teszt
=> [api clients] közösségek api kliens tesztek

assets/css/_bootstrap.scss, config/packages/twig.yaml, src/Controller/SecurityController.php, templates/security/login.html.twig, translations/messages.hu.yaml
=> [style] login oldal kinézete

config/routes.yaml, templates/base.html.twig, templates/static_page/about.twig
statikus oldalak felvetele a routeok koze
=> [static] statikus oldal routeok felvetele es javitas

src/Form/Types/LoginType.php, tests/ApplicationTests/Controller/SecurityControllerTest.php
=> [security] lemaradt LoginType #203

.github/workflows/lint.yml, .github/workflows/symfony.yml, docker/Dockerfile.build.miserend, docker/Dockerfile.miserend
docker es github workflow frissitese 83-ra
=> [docker/qa] frissites: php 83

.ci/github/phpunit/phpunit.xml.dist, .github/workflows/symfony.yml, README.md
codecov integráció
closes #199
=> [ci] codecov integráció

composer.json, phpunit.xml.dist, src/Components/ApiClients/BreviarKBSClient.php, src/Controller/LiturgicalDayController.php, templates/alerts/liturgical_day.html.twig, tests/ApplicationTests/Controller/LiturgicalDayControllerTest.php, tests/ApplicationTests/Controller/SecurityControllerTest.php, tests/ApplicationTests/Controller/UserControllerTest.php, tests/ApplicationTests/Fixtures/breviar_fq_cinerum_html.txt, tests/ApplicationTests/Fixtures/breviar_fq_cinerum_response.xml, tests/ApplicationTests/Fixtures/breviar_nativitatis_html.txt, tests/ApplicationTests/Fixtures/breviar_nativitatis_response.xml
- hamvazoszerda nem jol jelent meg, erre irtam tesztet
- hibas valasz teszteles
- 2 mp-re noveltem a timeoutot
=> [api kliensek] breviar kbs teszteles

bin/build.sh
=> [docker] build futtassa le a migraciot inditaskor

.github/workflows/static-analysis.yml, .gitignore, composer.json, phpstan.neon.dist, src/Controller/LiturgicalDayController.php, src/Controller/MapController.php, src/Entity/OsmTag.php, symfony.lock, tests/StaticAnalysis/object-manager.php
github workflow és alap beállítások
Az ellenőrzés level 1-en fut, a cél a level 9.
=> [qa] statikus analizálás phpstannal

composer.json, phpstan.neon.dist, phpunit.xml.dist, src/Components/AccessibilityHelper.php, src/Components/ApiClients/BreviarKBSClient.php, src/Components/ApiClients/Response/CommunitiesResponse.php, src/Components/ApiClients/Response/Community.php, src/Controller/FavoriteController.php, src/Controller/MapController.php, src/Entity/Church.php, src/Entity/ChurchHolder.php, src/Entity/User.php, src/Form/ChoiceLoaders/RoleChoiceLoader.php, src/Legacy/Services/ConstantsProvider.php, src/Repository/OsmTagRepository.php, src/Repository/PhotoRepository.php, src/Repository/UserRepository.php, src/Request/QueryParameterEntityResolver.php, tests/ApplicationTests/Controller/LiturgicalDayControllerTest.php, tests/ApplicationTests/Controller/UserControllerTest.php, tests/StaticAnalysis/phpstan-baseline.php, tests/Unit/Components/AccessibilityHelperTest.php, tests/Unit/Repository/UserRepositoryTest.php
level 6-ig elvittem két hibát leszámítva. folytatása lesz.
=> [qa] vegyes javitasok #222 followup

composer.json
=> [composer] precommit hivja az analysis-t is

docker/Dockerfile.build.miserend
Eljutottam oda, hogy telepítsek winre dockert. Küldöm a javításokat sorban.
=> [docker] hianyzo php kiterjesztesek telepitese

webapp/classes/api/nearby.php
=> Add limit parameter to nearby

webapp/classes/api/nearby.php, webapp/classes/eloquent/church.php
A nearby-nál meg lehet adni, hogy aktuális vagy vasárnapi miserendet kér az illető
=> Update with optional day

webapp/classes/eloquent/remark.php, webapp/classes/html/remark.php, webapp/functions.php, webapp/templates/email/remarkfeedback.twig, webapp/templates/remark_list.twig
=> go to prod
